### ISSUE TITLE
1.5-1.6 protocol support?

### ISSUE THREAD

**Issue by Zilacon** [WaterfallMC/Travertine#35]
I am looking for an all-in-one bungee solution for my entire network. And was hoping it would be possible for you guys to add 1.5-1.6 protocol support for waterfall?

(Yes i know its old, no i cant update because the modpacks are no longer being updated but thousands still play them)

I have 1.5.2, 1.6.4, 1.7.10, and 1.11.2 servers.

**Comment by kashike** [comment]
@fuzzybot

**Comment by Zilacon** [comment]
![Image of Hypocrisy](http://image.prntscr.com/image/5e0e3a52ab64423b8b011293a51e3a32.png)

"Terrible Idea" is written all over your repositories ReadMe then.

**Comment by MrPowerGamerBR** [comment]
@Zilacon use ProtocolSupportBungee... however it is not updated anymore so...

I think supporting 1.5/1.6 is waaaay more difficult than supporting 1.7 due to the protocol changes between 1.5/1.6 and 1.7. (1.5/1.6 didn't even use Netty!)

**Comment by Zilacon** [comment]
ProtocolSupportBungee does not work unless ProtocolSupport (the bukkit plugin) is placed on every server. Which is impossible since its coded for only 1.10.2+

Also this is the config from my 1.6.4 Agrarian Skies server:
````
config-version: 3
commands:
  spam-exclusions:
  - /skill
  log: false
  tab-complete: true
settings:
  prevent-proxies: false
  timeout-time: 60
  restart-on-crash: false
  restart-script: ./restart
  bungeecord-addresses:
  - xxx.xxx.xxx.xxx
  bungeecord: true
  *netty-threads: 4*
  log-filters:
  - ^(.*)(/logged in)(.*)$
````

As you can see 1.6.4 DOES have netty.
